apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: fabric-zk-kafka
  name: kafka3
spec:
  replicas: 1
  template:
    metadata:
      labels:
       app: hyperledger
       role: kafka
       kafka-id: kafka3
    spec:
      initContainers:
        - name: depend-on-zookeeper-cluster
          image: busybox:latest
          command: ['sh', '-c', "telnet zookeeper-0.zk-headless 2181 && telnet zookeeper-1.zk-headless 2181 && telnet zookeeper-2.zk-headless 2181"]
      containers:
        - name: kafka3
          image: hyperledger/fabric-kafka:latest
          env:
            - name: KAFKA_BROKER_ID
              value: "3"
            - name: KAFKA_MIN_INSYNC_REPLICAS
              value: "2"
            - name: KAFKA_DEFAULT_REPLICATION_FACTOR
              value: "3"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper-0.zk-headless:2181,zookeeper-1.zk-headless:2181,zookeeper-2.zk-headless:2181"
            - name: KAFKA_MESSAGE_MAX_BYTES
              value: "103809024"
            - name: KAFKA_REPLICA_FETCH_MAX_BYTES
              value: "103809024"
            - name: KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE
              value: "false"
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: "kafka3.fabric-zk-kafka"
---
apiVersion: v1
kind: Service
metadata:
   namespace: fabric-zk-kafka
   name: kafka3
spec:
 selector:
   app: hyperledger
   role: kafka
   kafka-id: kafka3
 clusterIP: None
 ports:
   - name: kafka-port1
     protocol: TCP
     port: 9092

   - name: kafka-port2
     protocol: TCP
     port: 9093